// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4LVQHedrLXvagCiKGWi46kgZYmnTkdA',
    appId: '1:976173368969:web:6fc0f684568f20293de858',
    messagingSenderId: '976173368969',
    projectId: 'friendz-code',
    authDomain: 'friendz-code.firebaseapp.com',
    storageBucket: 'friendz-code.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3h2uv72DYLen54BAHiP7qCAxMZNU8_As',
    appId: '1:976173368969:android:91eb3b9e7e4f45843de858',
    messagingSenderId: '976173368969',
    projectId: 'friendz-code',
    storageBucket: 'friendz-code.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCirukzmw-M7s6o1yDZbks15yte06ttNkk',
    appId: '1:976173368969:ios:7a59022965c32c1d3de858',
    messagingSenderId: '976173368969',
    projectId: 'friendz-code',
    storageBucket: 'friendz-code.appspot.com',
    iosBundleId: 'com.example.friendzCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCirukzmw-M7s6o1yDZbks15yte06ttNkk',
    appId: '1:976173368969:ios:2898768e3551be0e3de858',
    messagingSenderId: '976173368969',
    projectId: 'friendz-code',
    storageBucket: 'friendz-code.appspot.com',
    iosBundleId: 'com.example.friendzCode.RunnerTests',
  );
}
